// Generated by CoffeeScript 2.1.1
var CFX;

import {
  prefixDom
} from 'cfx.dom';

import Title from './title';

import Input from './input';

import List from './list';

CFX = prefixDom({'div': 'div', Title, Input, List});

export default function() {
  var c_Input, c_List, c_Title, c_div;
  ({c_div, c_Title, c_Input, c_List} = CFX);
  return c_div({}, c_Title({}), c_Input({}), c_List({
    data: [
      {
        objectId: 0,
        todo: '完成',
        isCompleted: true
      },
      {
        objectId: 1,
        todo: '未完成',
        isCompleted: false
      }
    ],
    styleChange: (function(objectId, isCompleted) {
      if (isCompleted === true) {
        return {
          textDecorationLine: 'line-through',
          opacity: 0.4
        };
      }
    }).bind(this),
    hasClick: function(str) {
      console.log('key:');
      return console.log(str);
    }
  }));
};
