// Generated by CoffeeScript 2.1.1
var CFX;

import {
  prefixDom
} from 'cfx.dom';

import Title from './title';

import Input from './input';

import List from './list';

CFX = prefixDom({'div': 'div', Title, Input, List});

export default function() {
  var c_Input, c_List, c_Title, c_div;
  ({c_div, c_Title, c_Input, c_List} = CFX);
  return c_div({}, c_Title({}), c_Input({}), c_List({
    data: [
      {
        value: 0,
        label: '完成1'
      },
      {
        value: 1,
        label: '完成2'
      }
    ]
  }));
};
