// Generated by CoffeeScript 2.1.1
var CFX;

import {
  prefixDom
} from 'cfx.dom';

CFX = prefixDom({'h1': 'h1'});

export default function() {
  var c_h1;
  ({c_h1} = CFX);
  return c_h1({
    style: {
      fontSize: '20px',
      textAlign: 'left',
      fontWeight: '400',
      color: '#c7c7cc',
      padding: '30px'
    }
  }, 'Todos');
};
