// Generated by CoffeeScript 2.1.1
var CFX,
  _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };

import {
  prefixDom
} from 'cfx.dom';

import {
  Layout
} from 'antd';

CFX = prefixDom({Layout});

export default ({props = {}, layers = []}) => {
  var c_Layout, layerStyle;
  
  // props = 
  //   props: xxx
  //   layer: [

  //     withLayout: true
  //     children:
  //       c_H1 {}
  //       , 'Hello World!!!'

  //     c_H1 {}
  //     , 'Hello World!!!'

  //     withLayout: false
  //     children: c_CenterCard {}

  //   ]

  ({c_Layout} = CFX);
  layerStyle = {
    position: 'absolute',
    width: '100%',
    minHeight: '100vh'
  };
  return c_Layout.apply(null, [
    props,
    ...(layers.reduce((r,
    c) => {
      var ref;
      return [
        ...r,
        ...(c.child != null ? ((c.withLayout != null) && c.withLayout === false ? [c.child] : [
          c_Layout({
            style: _extends({},
          layerStyle,
          (((ref = c.layout) != null ? ref.style : void 0) != null ? c.layout.style : {}))
          },
          c.child)
        ]) : [
          c_Layout({
            style: layerStyle
          },
          c)
        ])
      ];
    },
    []))
  ]);
};
