// Generated by CoffeeScript 2.1.1
import PageCenter from './PageCenter';

import SiderContent from './SiderContent';

import Content from './Content';

export {
  PageCenter,
  SiderContent,
  Content
};
