// Generated by CoffeeScript 2.1.1
var CFX, StoryTodos, actions, mapActionToProps, mapStateToProps, reducers;

import {
  ddbs as dd
} from 'ddeyes';

import React, {
  Component
} from 'react';

import {
  List
} from 'StoryView';

import {
  prefixDom
} from 'cfx.dom';

import {
  connect
} from 'cfx.react-redux';

import {
  store
} from 'ReduxServ';

({actions, reducers} = store);

import {
  getState
} from './components';

CFX = prefixDom({List, 'div': 'div'});

StoryTodos = class StoryTodos extends Component {
  constructor(props) {
    super(props);
    this.state = {
      todos: props.state.todos,
      filter: props.state.filter
    };
    this;
  }

  componentWillMount() {
    this.props.actions.fetchAll();
    return this;
  }

  componentWillReceiveProps(nextProps) {
    var filter, todos;
    ({todos, filter} = nextProps.state);
    this.setState({todos, filter});
    return this;
  }

  render() {
    var Packet, c_List, c_div;
    ({c_div, c_List} = CFX);
    Packet = function(bool, data) {
      return data.reduce((r, c) => {
        return [...r, ...(c.isCompleted === bool ? [c] : [])];
      }, []);
    };
    return c_div({}, c_List({
      data: this.state.filter === 'active' ? Packet(false, this.state.todos) : this.state.filter === 'completed' ? Packet(true, this.state.todos) : this.state.todos,
      styleChange: (function(objectId, isCompleted) {
        if (isCompleted === true) {
          return {
            textDecorationLine: 'line-through',
            opacity: 0.4
          };
        }
      }).bind(this),
      Delete: (function(key) {
        // @props.actions.remove
        return this.props.actions.deleteOne({
          objectId: key
        });
      }).bind(this),
      hasClick: (function(key, todo, isCompleted) {
        return this.props.actions.update({
          // @props.actions.patch
          objectId: key,
          todo: todo,
          isCompleted: !isCompleted
        });
      }).bind(this),
      Patch: (function(key, value, isCompleted) {
        return this.props.actions.update({
          // @props.actions.patch            
          objectId: key,
          todo: value,
          isCompleted: isCompleted
        });
      }).bind(this)
    }));
  }

};

mapStateToProps = function(state) {
  return getState(state.todosRedux);
};

mapActionToProps = {
  deleteOne: actions.todoDelete,
  update: actions.todoUpdate,
  fetchAll: actions.todoFetchAll
};

// remove: actions.todoRemove
// patch: actions.todoPatch
export default connect(mapStateToProps, mapActionToProps, StoryTodos);
