// Generated by CoffeeScript 2.1.1
// import 'normalize.css/normalize.css'
// import 'reset-css/reset.css'
import Welcome from './Welcome';

import App from './App';

import Login from './Login';

Welcome();

App();

Login();
