// Generated by CoffeeScript 2.1.1
var CFX, actions, todosStore;

import {
  storiesOf
} from '@storybook/react';

import {
  prefixDom
} from 'cfx.dom';

import 'antd-mobile/dist/antd-mobile.css';

import List from '../components/list';

import {
  Provider
} from 'cfx.react-redux';

import {
  store
} from 'ReduxServ';

todosStore = store.store;

({actions} = store);

console.log(store.actions);

CFX = prefixDom({List, Provider});

export default function() {
  return storiesOf('Todos', module).addDecorator(function(story) {
    var c_Provider;
    // todosStore.dispatch store.actions.todosCreate
    //   id: 1
    //   todo: '123'
    //   isCompleted: false
    ({c_Provider} = CFX);
    return c_Provider({
      store: todosStore
    }, story());
  // .add 'Input'
  }).add('List', () => {
    var c_List;
    ({c_List} = CFX);
    return c_List({});
  });
};

// .add 'App'
