// Generated by CoffeeScript 2.1.1
var CFX;

import {
  storiesOf
} from '@storybook/react';

import {
  prefixDom
} from 'cfx.dom';

import Login from '../components/Login/Form';

import 'antd/dist/antd.css';

CFX = prefixDom({'div': 'div', Login});

export default function() {
  return storiesOf('LoginForm', module).add('index', () => {
    var c_Login;
    ({c_Login} = CFX);
    return c_Login({});
  });
};
