// Generated by CoffeeScript 2.1.1
var CFX;

import {
  storiesOf
} from '@storybook/react';

import {
  prefixDom
} from 'cfx.dom';

import 'antd-mobile/dist/antd-mobile.css';

import LoginForm from '../../components/Login/index';

CFX = prefixDom({LoginForm});

export default function() {
  return storiesOf('LoginForm', module).add('Index', () => {
    var c_LoginForm;
    ({c_LoginForm} = CFX);
    return c_LoginForm({});
  });
};
