// Generated by CoffeeScript 2.1.1
var CFX;

import {
  storiesOf
} from '@storybook/react';

import {
  prefixDom
} from 'cfx.dom';

import 'antd-mobile/dist/antd-mobile.css';

import Login from '../../components/Login/Form';

CFX = prefixDom({Login});

export default function() {
  return storiesOf('Login', module).add('Index', () => {
    var c_Login;
    ({c_Login} = CFX);
    return c_Login({});
  });
};
