// Generated by CoffeeScript 2.1.1
import '@storybook/addon-actions/register';

import '@storybook/addon-links/register';

import '@storybook/addon-events/register';

import '@storybook/addon-notes/register';

import '@storybook/addon-options/register';

import '@storybook/addon-knobs/register';
