// Generated by CoffeeScript 2.1.1
var CFX, Commit,
  _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };

import FormField from '../../Form/Field';

import {
  Button,
  Checkbox
} from 'antd';

import {
  prefixDom
} from 'cfx.dom';

import nb from './style';

CFX = prefixDom({'a': 'a', 'div': 'div', Button, Checkbox, FormField});

Commit = ({decorator}) => {
  var c_Button, c_Checkbox, c_FormField, c_a, c_div;
  ({c_a, c_div, c_Button, c_Checkbox, c_FormField} = CFX);
  return c_FormField({}, c_Button(_extends({
    type: 'primary',
    htmlType: 'submit'
  }, nb('loginFormButton')), '登录'), {
    decorator: decorator,
    name: 'remember',
    props: {
      valuePropName: 'checked',
      initialValue: true
    },
    children: c_Checkbox({}, '记住用户名')
  }, c_div(_extends({}, nb('loginFormForgot')), c_a({
    href: ''
  }, '忘记密码'), ' or ', c_a({
    href: ''
  }, '注册')));
};

export default Commit;
