// Generated by CoffeeScript 2.1.1
var CFX, LoginCard, enhance, hocMapProps,
  _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };

import {
  Card
} from 'antd';

import Form from './Form';

import {
  prefixDom
} from 'cfx.dom';

import {
  mapProps,
  compose
} from 'recompose';

CFX = prefixDom({Card, Form});

hocMapProps = mapProps((ownerProps) => {
  return _extends({}, ownerProps, {
    style: _extends({}, (ownerProps.style != null ? ownerProps.style : {}), {
      width: 300
    })
  });
});

enhance = compose(hocMapProps);

LoginCard = enhance((props) => {
  var c_Card, c_Form;
  ({c_Card, c_Form} = CFX);
  return c_Card(props, c_Form({}));
});

export default LoginCard;
