// Generated by CoffeeScript 2.1.1
// import { ddbs as dd } from 'ddeyes'
var CFX, CenterCard;

import PageCenter from '../Layout/PageCenter';

import LoginCard from './Card';

import {
  prefixDom
} from 'cfx.dom';

CFX = prefixDom({PageCenter, LoginCard});

CenterCard = (props) => {
  var c_LoginCard, c_PageCenter;
  ({c_PageCenter, c_LoginCard} = CFX);
  return c_PageCenter(props, c_LoginCard({}));
};

export default CenterCard;
