// Generated by CoffeeScript 2.1.1
var CFX, Login,
  _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };

import React, {
  Component
} from 'react';

import {
  prefixDom
} from 'cfx.dom';

import nb from './style';

import star from '../../../public/assets/demo-1-bg.jpg';

CFX = prefixDom({'div': 'div', 'form': 'form', 'h3': 'h3', 'span': 'span', 'input': 'input', 'img': 'img', 'a': 'a'});

Login = class Login extends Component {
  render() {
    var c_a, c_div, c_form, c_h3, c_img, c_input, c_span;
    ({c_div, c_form, c_h3, c_span, c_input, c_a, c_img} = CFX);
    return c_div({}, c_img({
      src: star
    }), c_div(_extends({}, nb('logo_box')), c_h3(_extends({}, nb('logo_box_h3')), '欢迎登陆'), c_form({
      action: '#',
      name: 'f',
      method: 'post'
    }, c_div(_extends({}, nb('input_outer')), c_span(_extends({}, nb('u_user'))), c_input(_extends({
      type: 'text',
      placeholder: '请输入账户',
      style: {
        color: '#FFFFFF'
      }
    }, nb('text')))), c_div(_extends({}, nb('input_outer')), c_span(_extends({}, nb('us_uer'))), c_input(_extends({
      type: 'password',
      placeholder: '请输入密码',
      style: {
        position: 'absolute',
        zIndex: '100',
        color: '#FFFFFF',
        value: ''
      }
    }, nb('text')))), c_div(_extends({}, nb('mb2')), c_a(_extends({
      style: {
        color: '#FFFFFF'
      },
      href: '#'
    }, nb('act_but'), nb('submit')), '登录')))));
  }

};

export default Login;
