// Generated by CoffeeScript 2.1.1
var CFX;

import {
  prefixDom
} from 'cfx.dom';

import React, {
  Component
} from 'react';

import {
  Login
} from 'cfx.antd-wrapper';

CFX = prefixDom({Login});

export default () => {
  var c_Login;
  ({c_Login} = CFX);
  return c_Login({});
};
