// Generated by CoffeeScript 2.1.1
var CFX, Item;

import React, {
  Component
} from 'react';

import {
  prefixDom
} from 'cfx.dom';

import {
  HotKeys
} from 'react-hotkeys';

import {
  List,
  InputItem,
  Switch,
  Stepper,
  Range,
  Button,
  WingBlank,
  WhiteSpace
} from 'antd-mobile';

({Item} = List);

import {
  createForm
} from 'rc-form';

CFX = prefixDom({'div': 'div', 'form': 'form', List, Item, InputItem, Button, WingBlank, WhiteSpace});

export default function() {
  return {
    render: function() {
      var c_Button, c_InputItem, c_Item, c_List, c_WhiteSpace, c_WingBlank, c_div, c_form;
      ({c_div, c_form, c_List, c_Item, c_InputItem, c_Button, c_WingBlank, c_WhiteSpace} = CFX);
      return c_form({}, c_List({}, c_Item({}, c_InputItem({
        clear: true,
        placeholder: '请输入用户名'
      }, '用户名:')), c_WhiteSpace({
        size: 'lg'
      }), c_Item({}, c_InputItem({
        clear: true,
        placeholder: '请输入密码',
        type: 'password'
      }, '密码:')), c_WhiteSpace({
        size: 'lg'
      }), c_Item({}, c_Button({
        type: 'primary',
        size: 'small',
        inline: true
      }, '登录'), c_Button({
        size: 'small',
        inline: true,
        style: {
          marginLeft: '2.5px'
        }
      }, '注册'))));
    }
  };
};
