// Generated by CoffeeScript 2.1.1
var CFX;

import {
  prefixDom
} from 'cfx.dom';

import CenterCard from './CenterCard';

import BackgroundImg from './background.jpg';

CFX = prefixDom({CenterCard});

export default () => {
  var c_CenterCard;
  ({c_CenterCard} = CFX);
  return c_CenterCard({
    style: {
      backgroundImage: `url(${(BackgroundImg.src != null ? BackgroundImg.src : BackgroundImg)})`
    }
  });
};
