// Generated by CoffeeScript 2.1.1
var CFX;

import {
  storiesOf
} from '@storybook/react';

import {
  prefixDom
} from 'cfx.dom';

import ListHave from '../../components/list';

CFX = prefixDom({ListHave});

export default function() {
  return storiesOf('TodosState', module).add('Have', () => {
    var c_ListHave;
    ({c_ListHave} = CFX);
    return c_ListHave({
      data: [
        {
          value: 0,
          label: '完成1'
        },
        {
          value: 1,
          label: '完成2'
        }
      ],
      creatList: function(data) {
        return console.log('hello');
      },
      isClick: true,
      str: '',
      hasClick: function(str) {
        console.log('key:');
        return console.log(str);
      }
    });
  });
};
