// Generated by CoffeeScript 2.1.1
var CFX;

import {
  storiesOf
} from '@storybook/react';

import {
  prefixDom
} from 'cfx.dom';

import ListNot from '../../components/Todos/list';

CFX = prefixDom({ListNot});

export default function() {
  return storiesOf('TodosState', module).add('Not', () => {
    var c_ListNot;
    ({c_ListNot} = CFX);
    return c_ListNot({
      data: [
        {
          objectId: 0,
          todo: '完成',
          isCompleted: true
        },
        {
          objectId: 1,
          todo: '未完成',
          isCompleted: false
        }
      ],
      styleChange: (function(objectId, isCompleted) {
        if (isCompleted === true) {
          return {
            textDecorationLine: 'line-through',
            opacity: 0.4
          };
        }
      }).bind(this),
      hasClick: function(str) {
        console.log('key:');
        return console.log(str);
      }
    });
  });
};
