// Generated by CoffeeScript 2.1.0
var getState, render;

render = function(CFX) {
  var c_Input;
  ({c_Input} = CFX);
  return c_Input({});
};

getState = function(state) {
  var filter;
  ({filter} = state);
  return {filter};
};

export {
  render,
  getState
};
