// Generated by CoffeeScript 2.1.1
var CFX, StoryTodos, actions, mapActionToProps, mapStateToProps, reducers, sagas;

import {
  ddbs as dd
} from 'ddeyes';

import React, {
  Component
} from 'react';

import {
  HotKeys
} from 'react-hotkeys';

import {
  Input
} from 'StoryView';

import {
  prefixDom
} from 'cfx.dom';

import {
  connect
} from 'cfx.react-redux';

import {
  store
} from 'ReduxServ';

({actions, reducers, sagas} = store);

import {
  getState
} from './components';

CFX = prefixDom({Input, HotKeys});

console.log(actions);

StoryTodos = class StoryTodos extends Component {
  constructor(props) {
    super(props);
    this.state = {
      todo: '',
      filter: props.state.filter
    };
    this;
  }

  componentWillReceiveProps(nextProps) {
    var filter;
    ({filter} = nextProps.state);
    this.setState({filter});
    return this;
  }

  render() {
    var c_HotKeys, c_Input;
    ({c_Input, c_HotKeys} = CFX);
    return c_HotKeys({
      keyMap: {
        submit: 'enter'
      },
      handlers: {
        submit: (function() {
          this.props.actions.create({
            todo: this.state.todo
          });
          // console.log @state.todo
          // @props.actions.create({todo: @state.todo}).then((result) =>{
          //   console.log(result)
          // })
          this.refs.RefInput.refs.RefInput.clearInput();
          return console.log(this.props);
        }).bind(this)
      }
    }, c_Input({
      ref: 'RefInput',
      filter: this.state.filter,
      selector: (function(filter) {
        return this.props.actions.filterSave({
          filter: filter
        });
      }).bind(this),
      onChange: (function(v) {
        return this.setState({
          todo: v
        });
      }).bind(this)
    }));
  }

};

mapStateToProps = function(state) {
  return getState(state.todosRedux);
};

mapActionToProps = {
  filterSave: actions.filterSave,
  // save: actions.todoSave
  create: actions.todoCreate
};

export default connect(mapStateToProps, mapActionToProps, StoryTodos);
