// Generated by CoffeeScript 2.1.1
var CFX, StoryTodos;

import {
  ddbs as dd
} from 'ddeyes';

import React, {
  Component
} from 'react';

import {
  Login
} from 'StoryView';

import {
  prefixDom
} from 'cfx.dom';

CFX = prefixDom({Login});

StoryTodos = class StoryTodos extends Component {
  constructor(props) {
    super(props);
    this;
  }

  render() {
    var c_Login;
    ({c_Login} = CFX);
    console.log(this.props);
    return c_Login({});
  }

};

export default StoryTodos;
