// Generated by CoffeeScript 2.1.1
// import { prefixDom } from 'cfx.dom'

// import LoginForm from './Form'
// # import LoginCard from './Card'
// # import CenterCard from './CenterCard'
// # import WithBackImg from './WithBackImg'
// # import WithBackCanvas from './WithBackCanvas'

// export {
//   LoginForm
//   # LoginCard
//   # CenterCard
//   # WithBackImg
//   # WithBackCanvas
// }

// export default WithBackCanvas

