// Generated by CoffeeScript 2.1.1
var CFX;

import {
  ddbs as dd
} from 'ddeyes';

import React, {
  Component
} from 'react';

import {
  Login
} from 'StoryView';

import {
  prefixDom
} from 'cfx.dom';

CFX = prefixDom({Login});

export default function() {
  return {
    render: function() {
      var c_Login;
      ({c_Login} = CFX);
      return c_Login({});
    }
  };
};
