// Generated by CoffeeScript 2.1.0
// import 'normalize.css/normalize.css'
// import 'reset-css/reset.css'
import Welcome from './Welcome';

import Todos from './todos';

import Input from './input';

import List from './list';

import todosActive from './todosActive';

import todosCom from './todosCom';

import todosAll from './todosAll';

Welcome();

Todos();

Input();

List();

todosActive();

todosCom();

todosAll();
