// Generated by CoffeeScript 2.1.1
// import 'normalize.css/normalize.css'
// import 'reset-css/reset.css'
import Welcome from './Welcome';

import Todos from './todos';

import Input from './input';

import List from './list';

import todosActive from './todosState/todosActive';

import todosCom from './todosState/todosCom';

import todosAll from './todosState/todosAll';

import todosHave from './todosState/todosHave';

import todosNot from './todosState/todosNot';

Welcome();

Todos();

Input();

List();

todosActive();

todosCom();

todosAll();

todosHave();

todosNot();
