// Generated by CoffeeScript 2.1.1
var CFX;

import {
  storiesOf
} from '@storybook/react';

import {
  prefixDom
} from 'cfx.dom';

import 'antd-mobile/dist/antd-mobile.css';

import List from '../components/list';

CFX = prefixDom({List});

export default function() {
  return storiesOf('Todos', module).add('List', () => {
    var c_List;
    ({c_List} = CFX);
    return c_List({
      data: [
        {
          objectId: 0,
          todo: '完成',
          isCompleted: true
        },
        {
          objectId: 1,
          todo: '未完成',
          isCompleted: false
        }
      ],
      styleChange: (function(objectId, isCompleted) {
        if (isCompleted === true) {
          return {
            textDecorationLine: 'line-through',
            opacity: 0.4
          };
        }
      }).bind(this),
      hasClick: function(str) {
        console.log('key:');
        return console.log(str);
      }
    });
  });
};
