// Generated by CoffeeScript 2.1.1
var CFX;

import {
  storiesOf
} from '@storybook/react';

import {
  prefixDom
} from 'cfx.dom';

import 'antd-mobile/dist/antd-mobile.css';

import List from '../components/list';

CFX = prefixDom({List});

export default function() {
  return storiesOf('Todos', module).add('List', () => {
    var c_List;
    ({c_List} = CFX);
    return c_List({});
  });
};
